package info.teksol.mindcode.webapp;

import org.springframework.jdbc.core.JdbcTemplate;

public class DbMigrator {
    public void migrate(JdbcTemplate template) {
        template.execute("""
                CREATE TABLE IF NOT EXISTS public.sources (
                  id         uuid primary key,
                  source     text                     not null,
                  created_at timestamp with time zone not null default current_timestamp
                )""");

        template.execute("ALTER TABLE public.sources ALTER COLUMN id SET DEFAULT gen_random_uuid()");
        template.execute("ALTER TABLE public.sources ADD COLUMN IF NOT EXISTS type text");
        template.execute("ALTER TABLE public.sources DROP COLUMN IF EXISTS use_count");

        template.execute("""
                CREATE TABLE IF NOT EXISTS public.errors (
                  id         uuid primary key,
                  version    text                     not null,
                  type       text                     not null,
                  source     text                     not null,
                  created_at timestamp with time zone not null default current_timestamp
                )""");

        template.execute("ALTER TABLE public.errors ALTER COLUMN id SET DEFAULT gen_random_uuid()");

        template.execute("""
                CREATE TABLE IF NOT EXISTS public.executions (
                  id                bigint generated by default as identity,
                  source_uuid       uuid,
                  type              text            not null,
                  source            text            not null,
                  node_count        integer         not null default 0,
                  module_count      integer         not null default 0,
                  unoptimized       integer         not null default 0,
                  optimized         integer         not null default 0,
                  parse_time        integer         not null default 0,
                  compile_time      integer         not null default 0,
                  optimize_Time     integer         not null default 0,
                  run_time          integer         not null default 0,
                  passes            integer         not null default 0,
                  error_count       integer         not null default 0,
                  warning_count     integer         not null default 0,
                  created_at        timestamp with time zone not null default current_timestamp
                )""");

        template.execute("DROP TABLE IF EXISTS public.users CASCADE");
        template.execute("DROP TABLE IF EXISTS public.scripts CASCADE");
        template.execute("DROP TABLE IF EXISTS public.script_versions CASCADE");
        template.execute("DROP TABLE IF EXISTS public.collections CASCADE");
        template.execute("DROP TABLE IF EXISTS public.collection_scripts CASCADE");
    }
}
