package info.teksol.mindcode.processor;

public enum ProcessorFlag {
    STOP_PROCESSOR_OPTIONAL,

    STOP_ON_END_INSTRUCTION,
    STOP_ON_PROGRAM_END,

    ERR_INVALID_COUNTER,
    ERR_INVALID_IDENTIFIER,
    ERR_UNSUPPORTED_OPCODE,
    ERR_UNINITIALIZED_VAR,
    ERR_ASSIGNMENT_TO_FIXED_VAR,
    ERR_NOT_AN_OBJECT,
    ERR_MEMORY_ACCESS,
    ERR_UNSUPPORTED_BLOCK_OPERATION,
    ERR_EXECUTION_LIMIT_EXCEEDED,

}
